name: Reusable - Test Environments

on:
  workflow_call:
    inputs:
      mensaje:
        required: true
        type: string

jobs:
  test:a:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje recibido
        run: echo "Mensaje recibido: ${{ inputs.mensaje }}"

      - name: Mostrar variables del environment
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "ENVIROMENT: ${{ vars.ENVIROMENT }}"

      - name: Usar el secret
        run: echo "Secret: ${{ secrets.MY_SECRET }}"
