name: Terraform apply

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      aws-role-name:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: us-east-1
      environment:
        required: true
        type: string
      terraform-version:
        required: false
        type: string
        default: 1.10.0

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/${{ inputs.aws-role-name }}
          aws-region: ${{ inputs.aws-region }}
          role-session-name: gha-tf-${{ github.actor }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend/${{ inputs.environment }}.conf
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      #- name: Generar override.auto.tfvars
      #  run: |
      #    echo "Generando override.auto.tfvars con secrets y vars..."
      #    cat <<EOF > override.auto.tfvars
      #    environment   = "${{ vars.TF_VAR_ENVIRONMENT }}"
      #    project_name  = "${{ vars.TF_VAR_PROJECT_NAME }}"
      #    rds_password  = "${{ secrets.TF_VAR_RDS_PASSWORD }}"
      #    EOF
      
      - name: Terraform apply 
        id: apply
        env:
          TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
          TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
          TF_VAR_rds_password: ${{ secrets.TF_VAR_RDS_PASSWORD }}
        run: terraform apply -auto-approve -var-file env/${{ inputs.environment }}.tfvars
