name: Terraform apply

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      aws-role-name:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: us-east-1
      environment:
        required: true
        type: string
      aditional-var-file:
        required: false
        type: string
        default: ''
      terraform-version:
        required: false
        type: string
        default: 1.10.0

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/${{ inputs.aws-role-name }}
          aws-region: ${{ inputs.aws-region }}
          role-session-name: gha-tf-${{ github.actor }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - uses: actions/download-artifact@v4
        if: inputs.aditional-var-file != ''
        with:
          name: ${{ inputs.aditional-var-file }}
          path: env/${{ inputs.environment }}-aditional.tfvars

      - name: Merge var files
        if: inputs.aditional-var-file != ''
        run: cat env/${{ inputs.aditional-var-file }}-aditional.tfvars >> env/${{ inputs.environment }}.tfvars
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend/${{ inputs.environment }}.conf
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform apply 
        id: apply
        run: terraform apply -auto-approve -var-file env/${{ inputs.environment }}.tfvars
